# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7176e881dfb997e21540512b810f2e50e53375a3643d370b8dfad59f6dddec647776df1a7a1abe660f63a352e0fda7585454603dfdd762f5fe52794b8a2d7adc

test:
  secret_key_base: 82644934cb569223169f26bbfc2321d1ed9fc624dea97e83310a8d641105ded2938668e4c1ade5a7e143b3d32fb56426457f0259e8cf183af15acb6d253354a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
